FROM oven/bun:1.3.5 AS builder

WORKDIR /app

COPY package.json bun.lock ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

COPY . .

RUN bun i --frozen-lockfile

RUN bun --filter ./backend build:client
RUN bun --filter ./frontend build:prod

FROM nginx:mainline-alpine3.23

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
