FROM oven/bun:1.3.5 AS builder

WORKDIR /app

COPY package.json bun.lock ./
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/

COPY . .

RUN bun i --frozen-lockfile

RUN bun build:prod

FROM oven/bun:1.3.5-slim

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=5656

COPY --from=builder /app/backend/dist/index.js ./dist/index.js
COPY --from=builder /app/backend/drizzle ./drizzle

EXPOSE 5656

CMD ["bun", "./dist/index.js"]
